CREATE SCHEMA IF NOT EXISTS pa;

DROP TABLE IF EXISTS pa.urls;
CREATE TABLE IF NOT EXISTS pa.urls (
    id SERIAL PRIMARY KEY,
    name VARCHAR(500) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS pa.url_checks;
CREATE TABLE IF NOT EXISTS pa.url_checks (
    id SERIAL PRIMARY KEY,
    url_id INTEGER NOT NULL REFERENCES pa.urls(id),
    status_code INTEGER NOT NULL,
    h1 TEXT,
    title TEXT,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);